# Generated by Django 5.1.7 on 2025-04-16 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdictionaries',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.profile'),
        ),
    ]
