# Generated by Django 5.1.7 on 2025-04-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_userdictionaries_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='count_words',
            new_name='number_half_learned_words',
        ),
        migrations.AddField(
            model_name='profile',
            name='number_words_studied',
            field=models.IntegerField(default=0),
        ),
    ]
