STUDY_NEW_WORD: str = "📚 Изучать новые слова"
HALF_LEARNED_WORD: str = "🌗 Слова выученные наполовину"
LEARNED_WORD: str = "🔄 Повторить изученные слова"
RATING: str = "🏆 Рейтинг"
HELP: str = "❓ Помощь"
KNOW: str = '😎 Знаю'
STUDY: str = '📝️ Изучать'
STOP_STUDY: str = '✋ Закончить упражнение'
START: str = '🚀 Поехали'
MENU: str = '📋 Меню'
